# Generated by Django 5.1.4 on 2025-02-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='executive_images/')),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('fb_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
