# Generated by Django 5.1.4 on 2025-02-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_api', '0003_updateandnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('date', models.DateField()),
            ],
        ),
    ]
