# Generated by Django 5.1.4 on 2025-02-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_api', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumanai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='alumanai_images/')),
                ('work_place', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_link', models.URLField()),
            ],
        ),
    ]
