# Generated by Django 5.1.4 on 2025-03-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_api', '0007_customuser_is_verified_customuser_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
